### ISSUE TITLE
remove the icon and exit

### ISSUE THREAD

**Issue by pcnate** [simonbuchan/node-not-the-systray#1]
Is there a built in but undocumented way to remove the icon because I wish to exit the application?

**Comment by pcnate** [comment]
no sure what I changed but it worked.

```javascript
    case ExitId:
      // Ids work in submenus too.
      console.log( "Exiting" );
      appIcon.remove()
      process.exit()
      break;
```

**Comment by simonbuchan** [comment]
Icons should be being removed when the process exits cleanly automatically - if you're by seeing that I might have to look into that.
