### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by lollita** [simonbuchan/node-not-the-systray#2]
When I try to compile it, I get:

```
SyntaxError: Unexpected token # in JSON at position 1221
    at JSON.parse (<anonymous>)
    at parseGyp (c:\node-not-the-systray-master\build.js:10:17)
    at main (c:\node-not-the-systray-master\build.js:27:29)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```
I am anyway able to compile binding.sln.

**Comment by simonbuchan** [comment]
That's confusing: `parseGyp()` has `.replace(/\#.+\n/, '')` to strip comments out before JSON.parse sees it? What commit are you on?

**Comment by simonbuchan** [comment]
Ugh. Easy fix, String.replace only replaces the first by default, the pattern needs a `g` flag to replace all. I'll quickly put that in, that should fix it for you.

**Comment by lollita** [comment]
Patch fix it.
Compliments for module.
ty.
