### ISSUE TITLE
Notification control

### ISSUE THREAD

**Issue by lollita** [simonbuchan/node-not-the-systray#3]
When I use:
appIcon.update({notification: {icon: appIcon.notificationIcon,title: "title",text: "body",realtime:false,respectQuietTime:false,sound:true}});
appIcon.update({notification: {icon: appIcon.notificationIcon,title: "title2",text: "body2",realtime:false,respectQuietTime:false,sound:true}});
It wait 5-6 seconds between two notify.
Do it possible change this interval, or remove notification programmatically or view both notifications?

**Comment by simonbuchan** [comment]
Closing as I'm pretty sure this is the native Windows behavior, sorry!
As far as I know there's no way to show notifications faster.
