### ISSUE TITLE
Allowing Base64Encoded Images

### ISSUE THREAD

**Issue by Tylerjet** [simonbuchan/node-not-the-systray#4]
when packaging with pkg the module cannot find the image in the virtual snapshot path and being able to use a base64Encoded string for the image would help that issue if possible.

**Comment by simonbuchan** [comment]
Unfortunately, this would be a bit of a pain in the ass to do.

At the moment images are loaded by windows using [`LoadImageW`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-loadimagew) here:

https://github.com/simonbuchan/node-not-the-systray/blob/ec563fc891752d17bbe27db0c2994050c77890be/src/icon-object.cc#L19-L20

So I can't really control how it loads from a path, using that.

To do this properly, I could add an implementation using something like [`CreateIconFromResourceEx`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createiconfromresourceex) which, as the name implies, takes the icon *resource* bits, which are different than what's in an `.ico` file: specifically, it only includes one "size" of the .ico file, see [this stack-overflow answer for some code](https://stackoverflow.com/questions/67342090/im-trying-to-do-a-resource-update-on-the-icons-of-a-windows-executable-and-im). So if you just want to give me a .ico file content, I would also have to reproduce the windows size lookup behavior, which I don't think is particularly well documented?

That said, for this purpose you may instead load from a windows resource of the current executable, using `Icon.loadResource(size, resource_id)`, possibly using [`rcedit`](https://github.com/electron/rcedit) to embed the icon resource after packaging, but this needs to be run on Windows, which is annoying for CI.

**Comment by Tylerjet** [comment]
Ahh ok thanks for the info, i do already have a workflow for changing the default icon for the executable using resource hacker would the id i set the icon be the same i use for the resource_id if i was using rcedit as well? If so i will definitely use that way instead as it will save me a bunch of time.

**Comment by simonbuchan** [comment]
Yep, though it looks like only number ids are supported at the moment, sorry!

**Comment by simonbuchan** [comment]
Note that `rcedit` is simply an example of a tool to edit the resources, you should be able to use Resource Hacker for this too, if you prefer.

**Comment by simonbuchan** [comment]
One more thing, IIRC, it would be the id of the ICONGROUP resource, not the individual ICON.

**Comment by Tylerjet** [comment]
Awesome yeah i was about to ask that when going through all the ids i currently see when just opening the exe in resource hacker ill def test it later today and see if it works out

**Comment by Tylerjet** [comment]
Absolutely perfect! Worked like a charm and you are indeed correct it is the icongroup id.
Closing as this solution is far better than original request

**Comment by simonbuchan** [comment]
Glad it worked out!
